import { spawn, spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { createServer } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";

const prepareScript = fileURLToPath(new URL("./prepare-env.mjs", import.meta.url));
const provisionScript = fileURLToPath(new URL("./provision-fastgpt-key.mjs", import.meta.url));
const template = fileURLToPath(new URL("./.env.identity-acceptance.example", import.meta.url));
const temporaryDirectories = [];

function runProvisioner(envFile) {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [provisionScript, envFile], {
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk) => { stdout += chunk; });
    child.stderr.on("data", (chunk) => { stderr += chunk; });
    child.on("close", (status) => resolve({ status, stdout, stderr }));
  });
}

afterEach(() => {
  while (temporaryDirectories.length > 0) rmSync(temporaryDirectories.pop(), { recursive: true, force: true });
});

describe("FastGPT acceptance key provisioning", () => {
  it("accepts the complete FULL_READ_ONLY catalog generated by prepare-env", async () => {
    const directory = mkdtempSync(join(tmpdir(), "fastgpt-provision-"));
    temporaryDirectories.push(directory);
    const envFile = join(directory, "acceptance.env");
    const prepared = spawnSync(process.execPath, [prepareScript, template, envFile], {
      encoding: "utf8",
      env: { ...process.env, IDENTITY_ACCEPTANCE_TOOL_MODE: "FULL_READ_ONLY" },
    });
    expect(prepared.status).toBe(0);

    const initialContent = readFileSync(envFile, "utf8");
    const businessTools = initialContent.match(/^MCP_TOOL_ALLOWLIST=(.*)$/m)?.[1].split(",") ?? [];
    const tools = [
      ...businessTools.map((name) => ({ name })),
      { name: "dachuan_identity_who_am_i", description: "Trusted identity" },
    ];
    const server = createServer((request, response) => {
      response.setHeader("content-type", "application/json");
      const data = request.url?.includes("preLogin") ? { code: "test-code" }
        : request.url?.includes("loginByPassword") ? { token: "test-token" }
          : request.url === "/api/core/app/mcpTools/getTools" ? tools
            : request.url === "/api/core/app/mcpTools/create" ? "a".repeat(24)
              : request.url === "/api/core/app/create" ? "b".repeat(24)
                : request.url === "/api/support/openapi/create" ? `fastgpt-${"c".repeat(32)}`
                  : {};
      response.end(JSON.stringify({ code: 200, data }));
    });

    await new Promise((resolve, reject) => {
      server.once("error", reject);
      server.listen(18081, "127.0.0.1", resolve);
    });
    try {
      const result = await runProvisioner(envFile);
      expect(result).toMatchObject({ status: 0, stderr: "" });
      expect(result.stdout).toContain("IDENTITY_ACCEPTANCE_FASTGPT_CONFIGURATION=PROVISIONED tools=25");
      expect(readFileSync(envFile, "utf8")).toMatch(/^AGENT_GATEWAY_FASTGPT_API_KEY=fastgpt-/m);
    } finally {
      await new Promise((resolve) => server.close(resolve));
    }
  });
});
